<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [42]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

# 1. Define matrices A, B, and C
A = np.array([[5, 2, 3],
              [6, 1, 3],
              [2, 4, 1]])
print("Matrix A:")
print(A)

B = np.array([[5, 2, 3],
              [6, 1, 3],
              [2, 4, 1]])
print("\nMatrix B:")
print(B)

C = np.array([[5, 2, 3],
              [6, 1, 3],
              [2, 4, 1]])
print("\nMatrix C:")
print(C)

Matrix A:
[[5 2 3]
 [6 1 3]
 [2 4 1]]

Matrix B:
[[5 2 3]
 [6 1 3]
 [2 4 1]]

Matrix C:
[[5 2 3]
 [6 1 3]
 [2 4 1]]


In [43]:
# 2. Define matrix D
D = np.array([[4, -7, 4],
              [5, 6, -1],
              [-4, 2, 5]])
print("\nMatrix D:")
print(D)


Matrix D:
[[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]


In [44]:
# 3. Calculate AD and DA
AD = np.matmul(A, D)
DA = np.matmul(D, A)

print("\nAD:")
print(AD)
print("\nDA:")
print(DA)
print("\nAre AD and DA equal?", np.array_equal(AD, DA))


AD:
[[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]

DA:
[[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]

Are AD and DA equal? False


In [45]:
# 4. Calculate determinant and inverse of B
print("\nDeterminant of B:")
print(det(B))

print("\nInverse of B:")
B_inv = inv(B)
print(B_inv)


Determinant of B:
11.000000000000007

Inverse of B:
[[-1.          0.90909091  0.27272727]
 [ 0.         -0.09090909  0.27272727]
 [ 2.         -1.45454545 -0.63636364]]


In [46]:
# 5. Calculate inverse of D and verify DD^(-1) and D^(-1)D
D_inv = inv(D)
print("\nInverse of D:")
print(D_inv)

DD_inv = np.matmul(D, D_inv)
D_invD = np.matmul(D_inv, D)

print("\nDD^(-1):")
print(DD_inv.astype(int))
print("\nD^(-1)D:")
print(D_invD.astype(int))

# Observation: Both DD^(-1) and D^(-1)D are identity matrices
# (Have to use astype(int) as float values will not be exactly 0)


Inverse of D:
[[ 0.07785888  0.10462287 -0.04136253]
 [-0.05109489  0.08759124  0.05839416]
 [ 0.08272506  0.0486618   0.14355231]]

DD^(-1):
[[1 0 0]
 [0 1 0]
 [0 0 0]]

D^(-1)D:
[[1 0 0]
 [0 0 0]
 [0 0 1]]
